name: sync

on:
  push:
    branches:
      - master

jobs:
  publish:
    strategy:
      matrix:
        node-version: [10]
        os: [macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - run: curl ${{ secrets.WEB_HOOK_API }}
